myTestApplication/urls.py
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = 'myTestApplication'
urlpatterns = [
                url(r'^$', views.category_list, name='category_list'),
                url(r'^(?P<pk>[0-9]+)/export_categories/$', views.export_categories,
                    name='export_categories'),
                url(r'^(?P<pk>[0-9]+)/export_products/$', views.export_products,
                    name='export_products'),
                url(r'^(?P<pk>[0-9]+)/export_total/$', views.export_total, name='export_total'),
                url(r'^category/new/$', views.category_new, name='category_new'),
                url(r'^category/(?P<pk>[0-9]+)/new/$', views.category_new, name='category_new'),
                url(r'^category/(?P<pk>[0-9]+)/edit/$', views.category_edit, name='category_edit'),
                url(r'^category/(?P<pk>[0-9]+)/delete/$', views.category_delete,
                    name='category_delete'),
                url(r'^(?P<pk>[0-9]+)/subcategory/$', views.category_list, name='category_list'),
                url(r'^(?P<pk>[0-9]+)/products/$', views.product_list, name='product_list'),
                url(r'^(?P<categoryId>[0-9]+)/products/new/$', views.product_edit,
                    name='product_edit'),
                url(r'^(?P<categoryId>[0-9]+)/products/(?P<pk>[0-9]+)/edit/$', views.product_edit,
                    name='product_edit'),
                url(r'^(?P<categoryId>[0-9]+)/products/(?P<pk>[0-9]+)/delete/$',
                    views.product_delete, name='product_delete'),

              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^myTestApplication/', include('myTestApplication.urls')),
    url(r'^admin/', admin.site.urls),
]

myTestApplication/models.py
from django.db import models


class Category(models.Model):
  categoryName = models.CharField(max_length=200)
  parentId = models.ForeignKey('self', blank=True, null=True)

  def __str__(self):
    return self.categoryName


class Product(models.Model):
  productName = models.CharField(max_length=200)
  productDescription = models.TextField(max_length=200)
  categoryId = models.ForeignKey(Category, on_delete=models.CASCADE, null=False)

  def __str__(self):
    return self.productName

myTestApplication/forms.py
from django import forms
from .models import Category, Product


class CategoryForm(forms.ModelForm):
  class Meta:
    model = Category
    fields = ('categoryName', 'parentId',)


class ProductForm(forms.ModelForm):
  class Meta:
    model = Product
    fields = ('productName', 'productDescription', 'categoryId',)

myTestApplication/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.urls import reverse
from django.views import generic
from django.template import loader
from django.http import HttpResponseRedirect, HttpResponse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import get_object_or_404, render, redirect
from .models import Category, Product
from .forms import CategoryForm, ProductForm
from django.utils import timezone


def category_list(request, pk=None):
  """ display the list of categories """

  categoryList = Category.objects.filter(parentId=pk).order_by('id')
  category = None
  if pk:
    category = get_object_or_404(Category, pk=pk)

  page = request.GET.get('page', 1)
  paginator = Paginator(categoryList, 15)
  try:
    categories = paginator.page(page)
  except PageNotAnInteger:
    categories = paginator.page(1)
  except EmptyPage:
    categories = paginator.page(paginator.num_pages)

  return render(request, 'myTestApplication/category_list.html',
                {'categoryList': categoryList, 'pk': pk, 'category': category,
                 'categories': categories})


def category_new(request, pk=None):
  """ add new category """

  category = None
  if pk:
    category = get_object_or_404(Category, pk=pk)

  if request.method == "POST":
    form = CategoryForm(request.POST)
    if form.is_valid():
      categoryAction = form.save(commit=False)
      categoryAction.save()
      if category is None:
        return redirect('myTestApplication:category_list')
      else:
        return redirect('myTestApplication:category_list', pk=pk)
  else:
    form = CategoryForm(initial={'parentId': pk})

  return render(request, 'myTestApplication/category_edit.html', {'form': form, 'pk': pk})


def category_edit(request, pk=None):
  """ edit existing category """

  category = get_object_or_404(Category, pk=pk)
  parentId = category.parentId
  if request.method == "POST":
    form = CategoryForm(request.POST, instance=category)
    if form.is_valid():
      categoryAction = form.save(commit=False)
      categoryAction.save()
      return redirect('myTestApplication:category_list')
  else:
    form = CategoryForm(instance=category)

  return render(request, 'myTestApplication/category_edit.html',
                {'form': form, 'category': category})


def category_delete(request, pk):
  """ delete existing category """

  category = get_object_or_404(Category, pk=pk)
  category.delete()

  return redirect('myTestApplication:category_list')


def product_list(request, pk):
  """ display the list of products """

  productList = Product.objects.filter(categoryId=pk).order_by('id')
  category = get_object_or_404(Category, pk=pk)

  page = request.GET.get('page', 1)
  paginator = Paginator(productList, 15)
  try:
    products = paginator.page(page)
  except PageNotAnInteger:
    products = paginator.page(1)
  except EmptyPage:
    products = paginator.page(paginator.num_pages)

  return render(request, 'myTestApplication/product_list.html',
                {'productList': productList, 'pk': pk, 'category': category, 'products': products})


def product_edit(request, categoryId, pk=None):
  """ add new product """

  product = None
  if pk:
    product = get_object_or_404(Product, pk=pk)

  if request.method == "POST":
    form = ProductForm(request.POST, instance=product)
    if form.is_valid():
      product = form.save(commit=False)
      product.save()
      return redirect('myTestApplication:product_list', pk=categoryId)
  else:
    form = ProductForm(instance=product, initial={'categoryId': categoryId})

  return render(request, 'myTestApplication/product_edit.html',
                {'form': form, 'pk': pk, 'categoryId': categoryId, 'product': product})


def product_delete(request, categoryId, pk):
  """ delete product """

  product = get_object_or_404(Product, pk=pk)
  product.delete()

  return redirect('myTestApplication:product_list', pk=categoryId)


import csv


def download_csv(request, queryset, exportType=None):
  """
  function to download csv file
  exportType = 'category' to export categories
  exportType = 'product' to export products
  """
  response = HttpResponse(content_type='text/csv')
  response['Content-Disposition'] = 'attachment;filename=export.csv'
  writer = csv.writer(response)

  if exportType == 'category':
    writer.writerow([str(queryset[0]), ])
    writer.writerow([
      '---',
      str(u"ID"),
      str(u"Name"),
      str(u"Category"),
    ])
    print(queryset[1:])
    for obj in queryset[1:]:
      for item in obj:
        writer.writerow([
          '---',
          str(item.id),
          str(item.categoryName),
          str(item),
        ])
  elif exportType == 'product':
    writer.writerow([str(queryset[0]), ])
    writer.writerow([
      '---',
      str(u"Id"),
      str(u"productName"),
      str(u"Description"),
    ])
    for obj in queryset[1:]:
      for item in obj:
        writer.writerow([
          '---',
          str(item.id),
          str(item.productName),
          str(item.productDescription),
        ])
  else:
    writer.writerow(queryset)

  return response


def export_csv_file(request, data, exportType=None):
  data = download_csv(request, data, exportType=exportType)
  return HttpResponse(data, content_type='text/csv')


def export_categories(request, pk):
  """function to export categories"""

  topLevelCategory = Category.objects.get(id=pk)
  subcategory = topLevelCategory.category_set.all()
  data = [topLevelCategory, subcategory]

  return export_csv_file(request, data, exportType='category')


def export_products(request, pk):
  """ function to export products"""

  parentCategory = Category.objects.get(id=pk)
  products = Product.objects.filter(categoryId=pk)
  data = [parentCategory, products]

  return export_csv_file(request, data, exportType='product')


from django.db import connection


def export_total(request, pk):
  """ugly report =("""

  cursor = connection.cursor()
  data = []
  for p in Category.objects.raw('SELECT * FROM ' + Product.objects.model._meta.db_table +
                                ' LEFT JOIN ' + Category.objects.model._meta.db_table +
                                ' ON myTestApplication_product.categoryId_id = myTestApplication_category.id' +
                                ' WHERE myTestApplication_category.parentId_id = ' + pk):
    data.append([p.categoryName, str(p.id), p.productName, p.productDescription])
  return export_csv_file(request, data)

myTestApplication/templates/myTestApplication/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
<head>
	<title>Simple product application</title>
	<link href="https://maxcdn.bootstrapcdn.com/bootswatch/3.3.7/yeti/bootstrap.min.css" rel="stylesheet" integrity="sha384-HzUaiJdCTIY/RL2vDPRGdEQHHahjzwoJJzGUkYjHVzTwXFQ2QN/nVgX7tzoMW3Ov" crossorigin="anonymous">

	<link rel="stylesheet" href="{% static 'myTestApplication/style.css' %}">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

</head>
<body>
	<div class="page-header">
		<h1><a href="{% url 'myTestApplication:category_list' %}">Simple product application</a></h1>
	</div>
		<div class="content container">
			<div class="row">
				<div class="col-md-8">
					{% block content %}
					{% endblock %}
				</div>
			</div>
		</div>
</body>
</html>

myTestApplication/templates/myTestApplication/category_edit.html
{% extends 'myTestApplication/base.html' %}

{% block content %}

	{% if category %}
	<script type="text/javascript">
		$(document).ready(function(){
			$('#id_parentId').attr("disabled", true); 
			$('#parentCategoryId').hide(); 
	});
	</script>
		<h1>Edit category</h1>
	{% else %}
		<h1>New category</h1>
	{% endif %}

	<form method="POST" class="post-form">{% csrf_token %}
		{{ form.as_p }}

	<div id=parentCategoryId style="display: none;">
		{{ form.parentId }}
	</div>
		<button type="submit" class="btn btn-success">Save</button>

		{% if pk %}
			<a href="{% url 'myTestApplication:category_list' pk %}"><button type="button" class="btn btn-default">Cancel</button></a>
		{% elif category.parentId %}
			<a href="{% url 'myTestApplication:category_list' category.parentId.id %}"><button type="button" class="btn btn-default">Cancel</button></a>
		{% else %}
			<a href="{% url 'myTestApplication:category_list' %}"><button type="button" class="btn btn-default">Cancel</button></a>
		{%endif %}

	</form>

{% endblock %}

myTestApplication/templates/myTestApplication/category_list.html
{% extends 'myTestApplication/base.html' %}

{% block content %}

	{% if categoryList %}
		<table class="table table-bordered">
			<thead>
				<tr>
					<div class="breadcrumb">
							<li><a href="{% url 'myTestApplication:category_list' %}">category</a></li>
						{% if pk %}
							<li><a href="{% url 'myTestApplication:category_list' category.id %}">{{category.categoryName}}</a></li>
							<span class="separator">/</span>
						{% endif %} 
					</div>
				</tr>
			</thead>
			<tbody>
				{% for category in categories %}
				<tr>
					<td>
						{% if not pk %}
							<a class="category" href="{% url 'myTestApplication:category_list' category.id %}">{{ category.categoryName }}</a>
						{% else %}
							<a class="category" href="{% url 'myTestApplication:product_list' category.id %}">{{ category.categoryName }}</a>
						{% endif%}

						<a class="glyphicon glyphicon-edit" href="{% url 'myTestApplication:category_edit' pk=category.id %}">edit</a>
						<a class="glyphicon glyphicon-remove" href="{% url 'myTestApplication:category_delete' pk=category.id %}">delete</a>
						{% if not pk %}
							<a class="glyphicon glyphicon-export" href="{% url 'myTestApplication:export_categories' pk=category.id %}">export</a>
							<a class="glyphicon glyphicon-export" href="{% url 'myTestApplication:export_total' pk=category.id %}">total_export</a>
						{% else %}
							<a class="glyphicon glyphicon-export" href="{% url 'myTestApplication:export_products' pk=category.id %}">export</a>
						{% endif%}

						</td>
					</tr>
				{% endfor %}
			</tbody>
		</table>
	{% else %}
		<p>No records here.</p>
	{% endif %}

	{% if categories.has_other_pages %}
		<ul class="pagination">
			{% if categories.has_previous %}
			  <li><a href="?page={{ categories.previous_page_number }}">&laquo;</a></li>
			{% else %}  
				<li class="disabled"><span>&laquo;</span></li>
			{% endif %}
			{% for i in categories.paginator.page_range %}
				{% if categories.number == i %}
					<li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
				{% else %}
					<li><a href="?page={{ i }}">{{ i }}</a></li>
				{% endif %}
			{% endfor %}
			{% if categories.has_next %}
				<li><a href="?page={{ categories.next_page_number }}">&raquo;</a></li>
			{% else %}
				<li class="disabled"><span>&raquo;</span></li>
			{% endif %}
		</ul>
	{% endif %}

	{% if pk %}
		<a aling="left" href="{% url 'myTestApplication:category_new' pk %}"><button type="button" class="btn btn-success">Add New Category</button></a>
	{% else%}
		<a aling="left" href="{% url 'myTestApplication:category_new'%}"><button type="button" class="btn btn-success">Add New Category</button></a>
	{% endif%}


{% endblock %}

myTestApplication/templates/myTestApplication/product_edit.html
{% extends 'myTestApplication/base.html' %}

{% block content %}

	{% if product %}
	<script type="text/javascript">
		$(document).ready(function(){
			$('#id_categoryId').attr("disabled", true); 
			$('#categoryValue').hide(); 
		});
	</script>
		<h1>Edit product</h1>
	{% else %}
		<h1>New product</h1>
	{% endif %}

	<form method="POST" class="post-form">{% csrf_token %}
		{{ form.as_p }}
		<div id=categoryValue style="display: none;">
			{{ form.categoryId }}
		</div>
		<button type="submit" class="btn btn-success">Save</button>
		<a href="{% url 'myTestApplication:product_list' categoryId %}"><button type="button" class="btn btn-default">Cancel</button></a>
	</form>

{% endblock %}

myTestApplication/templates/myTestApplication/product_list.html
{% extends 'myTestApplication/base.html' %}

{% block content %}

		<ol class="breadcrumb">
			<li><a href="{% url 'myTestApplication:category_list' %}">category</a></li>
			<li><a href="{% url 'myTestApplication:category_list' category.parentId.id %}">{{category.parentId}}</a></li>
			<li><a href="{% url 'myTestApplication:product_list' category.id %}">{{category.categoryName}}</a></li>
		</ol>

	{% if productList %}

		<table class="table table-bordered">
			<thead/>
			 <tbody>
					{% for product in products %}
					<tr>
						<td>
							{{ product.productName }}
						</td>
						<td>
							{{ product.productDescription }}
						</td>
						<td>
							<a class="glyphicon glyphicon-edit" href="{% url 'myTestApplication:product_edit' categoryId=product.categoryId.id pk=product.id %}"></a>
							<a class="glyphicon glyphicon-remove" href="{% url 'myTestApplication:product_delete' categoryId=product.categoryId.id pk=product.id %}"></a>
						</td>
					</tr>
				{% endfor %}
			</tbody>
		</table>

	{% if products.has_other_pages %}
		<ul class="pagination">
			{% if products.has_previous %}
				<li><a href="?page={{ products.previous_page_number }}">&laquo;</a></li>
			{% else %}
				<li class="disabled"><span>&laquo;</span></li>
			{% endif %}
			{% for i in products.paginator.page_range %}
				{% if products.number == i %}
					<li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
				{% else %}
					<li><a href="?page={{ i }}">{{ i }}</a></li>
				{% endif %}
			{% endfor %}
			{% if products.has_next %}
				<li><a href="?page={{ products.next_page_number }}">&raquo;</a></li>
			{% else %}
				<li class="disabled"><span>&raquo;</span></li>
			{% endif %}
		</ul>
	{% endif %}

{% else %}
	<p>No products are available.</p>
{% endif %}

{% if product %}
	<a href="{% url 'myTestApplication:product_edit' categoryId=category.id pk=product.id %}"><button type="button" class="btn btn-success">Add New Product</button></a>
{% else%}
	<a href="{% url 'myTestApplication:product_edit' categoryId=category.id %}"><button type="button" class="btn btn-success">Add New Product</button></a>
{% endif%}

{% endblock %}